### PR TITLE
Pfifo

### PR DESCRIPTION
**Pull request by pfifo**
it should be safe to pull this now, unless there is a way to delete the fist commit all together

### CODE REVIEW

**Comment by kev009** [comment]
I'd like to retain a couple of the points in my original merge, mainly using macros for native big endian machines.

Also (maybe because I haven't slept much) but this doesn't handle floating point code at all?  IEEE754 states that you will have a significand and an exponent.  For doubles, that means byte swapping the two bytes, storing that to the result, then swapping the next two bytes and storing that.  I believe my float code is broken wrt this as well.

Let me mull over this for a bit and get back to you.

**Comment by pfifo** [comment]
the bytes dedicated to storing the information and the way they are written to the file have nothing todo with each other. For doubles its not what you are describing at all. Still if you think a macro provides a better interface then might as well use it. but it would be nice to have all endianness taken care of with just one macro if possible.

I myself shy away from using the networking calls as they really arent made for this even though they do pretty much give the same result.

gcc has an intrinsic called __byteswap, that works with a single line of assembly, but only for a 32bit number and only for i386, and I have no idea if it works the same on a 64bit machine. It could be twisted to work for 64bit numbers but would require several calls.

**Comment by kev009** [comment]
Doubles are 100% stored like this, check out wikipedia or this http://www.dmh2000.com/cpp/dswap.shtml.  "The moral of this story is that floating point data types aren't just big integers."

Using htons/ntohs, htonl/ntohl is advised for any internal implementation.  These are commonly macros and C libraries often implement them using the compiler intrinsic you mention, so it's a portable way for maximum performance.  Look at endian.h from glibc.

No real problem with condensing down the number of interfaces.  However, in practice having to pass in sizeof() for every call is counterproductive and will result in more code.  Something like Cswap16, Cswap32, Cswap64, Cswapf16, Cswapf32 would make more sense.

**Comment by pfifo** [comment]
Ive never thought about it like that, or tested it. I know my function works perfect in 'Duty free store' mode where you read data in from a file, convert it to a double via a character array. and then recast to a double to be loaded into the FPU. and vica versa, cast to a char array and swapped, then immediately written to a file. I suspect that loading the swapped format in the FPU could actually change the bits. However doing this with any of the other macros will produce the same result.

They way i see the process is like this. Read BE data from file, swap and recast BE character array to LE double, work with double in native endiness, recast double to char array, swap bytes, write to file. If for one reason or another were trying to work with this data in non-machine format then were going to have alot of difficulties.

And I am SURE that the byte order is simply reversed 0,1,2,3,4,5,6,7 converts to 7,6,5,4,3,2,1,0 NOT 6,7,4,5,2,3,0,1. Ive compared the results byte for byte converting Notch's test files against the code. At for ieee754 first I thought that exponent and manitissa would present a problem also but as it turns out groups of 8 >BITS< remain the same order, its just the >BYTES< that are reversed

at anyrate, im haveing alot of trouble picking up on git, by the time im actually able to keep up with commits and changes, you will have the whole issue resolved.

**Comment by kev009** [comment]
Alright, I redid this with input from you and Reductor.  The interface is hton{s,l,ll}, ntoh{s,l,ll}, Cswapf, Cswapd.

I rely on autoconf to try and select an OS implementation in hopes that the 64-bit operation is defined atomically, but otherwise fall back to a bitshift and use htonl for htonll.

The float/double routines incur two memcpys but should be safer than other methods, especially with respect to memory alignment issues.  It still sidesteps the issue in that link above, but hopefully this is "good enough" and we can check once we start sending chunks.

**Pull request closed without merging**
